import "./about.css";

const About: React.FC = () => {

  return (
    <>
      <article>
        Images are AI generated art.
        Generated by: InvokeAI
        Images are not copyright or being sold.
        No rights reserved.
      </article>
    </>
  );
};

export default About;